### ISSUE TITLE
Introduce the Web API to list catalogs of the books before purchase

### ISSUE THREAD

**Issue by lulzneko** [riotz-works/prototypes-quiz#10]
購入前書籍 の 一覧を取得する Web API を 導入します。
まずは一覧を返すのみで、クエリやページネーションは別途。
```
      - http:
          method: get
          path: catalogs
          cors: true
```
