### ISSUE TITLE
Introduce Web API to get a list of purchased books

### ISSUE THREAD

**Issue by lulzneko** [riotz-works/prototypes-quiz#11]
購入した書籍 の 一覧を取得する Web API を 導入します。
まずは一覧を返すのみで、クエリやページネーションは別途。
本来は認証が必要な API となりますが、認証基盤導入までは認証なしとします。
```
      - http:
          method: get
          path: books
          cors: true
```
